[ssh]
user = "root"
key = "/home/ubuntu/.ssh/id_rsa"

[deploy.bankgw-api]
server = ["192.168.2.228"]
remote_dir = "/opt/project/bankgw/bankgw-api"
backup_dir = "/opt/project/backup"
local_dir = "/mnt/d/项目/git/bankgw/bankgw-api/target/bankgw-api"
exclude = ["logs","log","tmp","temp","*.log","*.logs"]
restart_cmd = "docker restart bankgw-api"
bind-port = 7102

[deploy.bankgw-job]
server = ["192.168.2.228"]
remote_dir = "/opt/project/bankgw/bankgw-job"
backup_dir = "/opt/project/backup"
local_dir = "/mnt/d/项目/git/bankgw/bankgw-job/target/bankgw-job"
exclude = ["logs","log","tmp","temp","*.log","*.logs"]
restart_cmd = "docker restart bankgw-job"
bind-port = [7103,9000]

[deploy.chatgpt-pdf]
server = ["192.168.2.228","192.168.2.100"]
remote_dir = "/opt/project/chatgpt-pdf"
backup_dir = "/opt/project/backup"
local_dir = "/mnt/f/软件项目/deploy-tool/data/chatgpt-pdf"
exclude = ["logs","log","tmp","temp","*.log","*.logs",".venv"]
restart_cmd = "docker restart chatgpt-pdf"
bind-port = [8501]

[command."备份Mysql数据库"]
server = ["192.168.2.228"]
command = "docker --version"
group = "备份数据库"

[command."自定义脚本1"]
server = ["192.168.2.228"]
command = "bash /root/a.shell"
group = "备份数据库"
